name: Test micrograd ports

on:
  push:
    paths:
      - '.github/workflows/test-micrograd-swift.yaml'
      - 'micrograd-swift/**'

jobs:
  build:
    name: Test micrograd-swift
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        working-directory: ./micrograd-swift
        run: swift build
      - name: Run tests
        working-directory: ./micrograd-swift
        run: swift test
