name: Test micrograd ports

on:
  push:
    paths:
      - '.github/workflows/test-micrograd-ports.yaml'
      - 'micrograd-swift/**'
      - 'micrograd-haskell/**'

jobs:
  test-micrograd-swift:
    name: Test micrograd-swift
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        working-directory: micrograd-swift/MicrogradSwift
        run: swift build
      - name: Run tests
        working-directory: micrograd-swift/MicrogradSwift
        run: swift test
  test-micrograd-haskell:
    name: Test micrograd-haskell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.2.7'
          enable-stack: true
          stack-version: 'latest'
      - name: Run tests
        working-directory: micrograd-haskell
        run: stack test
